2018-09-29 00:40:30.174232Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.838 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x758907d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-29 01:00:00.833105Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec36b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-29 01:11:07.478743Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.786 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3f30>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-29 01:12:57.950259Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3e50>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-29 01:14:49.309872Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3250>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-29 01:29:38.989905Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0df0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-29 02:51:48.922816Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0090>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-29 02:55:30.738775Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed56d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 03:06:36.953688Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3af0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 03:15:58.167051Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed07b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 03:27:04.597432Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75890e30>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-29 03:32:42.578972Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0650>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 03:40:11.797599Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec38f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 03:56:57.622340Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0c90>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 04:04:26.991646Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0210>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 04:08:08.699076Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed09f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 04:11:56.402313Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0d10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 04:17:34.285882Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed00f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 04:19:29.858615Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed03b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 05:02:24.422546Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=20.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0830>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 05:48:50.582620Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=19.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3850>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 06:33:24.351400Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=19.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec35d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 08:24:39.577736Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3b90>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 08:26:30.130989Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=21.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3ed0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-29 08:30:11.752927Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=21.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0ff0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 08:33:53.637306Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=21.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed0170>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-29 09:49:54.857740Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3370>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 09:51:45.360918Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3570>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 09:55:27.078977Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec3f70>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-29 10:02:51.122357Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed01f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 10:10:20.366053Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.226 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74edeeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 10:14:02.028388Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ede7b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 10:39:58.068890Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ec38d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 11:58:18.592097Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ede990>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 12:00:14.024164Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ede190>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 12:02:09.457300Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.096 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ede3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-29 12:35:51.898107Error Connecting:ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74ed5090>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-30 02:46:13.332833 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.56&api_key=2SN2O4NEQJ4UZ84T&field1=19.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 02:49:17.647823 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.56&api_key=2SN2O4NEQJ4UZ84T&field1=19.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43a70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 02:52:22.852614 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.536&api_key=2SN2O4NEQJ4UZ84T&field1=19.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43330>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 02:55:27.007507 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.5&api_key=2SN2O4NEQJ4UZ84T&field1=19.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 02:58:31.239092 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.5&api_key=2SN2O4NEQJ4UZ84T&field1=19.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43ef0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:01:35.452958 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.5&api_key=2SN2O4NEQJ4UZ84T&field1=19.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43270>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:04:39.772776 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.5&api_key=2SN2O4NEQJ4UZ84T&field1=19.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3cc90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:07:44.844665 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.5&api_key=2SN2O4NEQJ4UZ84T&field1=19.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c0b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:10:49.163823 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.5&api_key=2SN2O4NEQJ4UZ84T&field1=19.352 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c8b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:13:52.610736 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.44&api_key=2SN2O4NEQJ4UZ84T&field1=19.324 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43ab0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:16:56.929305 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.44&api_key=2SN2O4NEQJ4UZ84T&field1=19.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:20:02.124677 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.44&api_key=2SN2O4NEQJ4UZ84T&field1=19.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:23:05.569083 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.44&api_key=2SN2O4NEQJ4UZ84T&field1=19.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:26:08.928652 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.44&api_key=2SN2O4NEQJ4UZ84T&field1=19.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:29:13.168305 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c270>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:32:16.609294 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:35:19.969268 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c5f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:38:25.247572 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f482b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:41:28.607387 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:44:32.056018 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:47:35.492817 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.38&api_key=2SN2O4NEQJ4UZ84T&field1=19.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:50:38.867112 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3cc30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:53:42.292533 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:56:45.742296 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43770>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 03:59:49.102704 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:02:52.540267 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f436b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:05:55.939547 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:08:59.347020 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.31&api_key=2SN2O4NEQJ4UZ84T&field1=19.148 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:12:02.862600 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.274&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f436f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:15:07.167590 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.25&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:18:10.607268 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.25&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f431d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:21:14.932689 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.25&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43fb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:24:19.252658 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.25&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:27:23.407765 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.25&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57cef50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:30:27.732739 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.096 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57ced70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:33:31.168889 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e3d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:36:36.287187 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e3e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:39:41.509983 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:42:45.008397 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:45:48.449461 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48cb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:48:53.652704 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.176&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:51:57.972858 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f480f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:55:01.433610 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 04:58:04.953565 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:01:09.412713 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:04:12.799382 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f543d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:07:17.973033 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48030>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:10:22.212707 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=18.964 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57cef10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:13:25.652704 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=18.964 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:16:29.100104 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f435b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:19:32.633568 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f436f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:22:36.153619 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:25:41.492783 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:28:45.032988 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:31:49.352846 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:34:54.692906 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:37:59.032700 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:41:03.512787 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c270>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:44:07.012735 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c530>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:47:11.332900 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.916 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:50:15.672944 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:53:20.772800 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.916 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:56:25.972714 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.904 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 05:59:30.292961 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c0b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:02:34.632900 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:05:39.833559 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f543f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:08:44.132826 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:11:48.452781 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.904 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54470>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:14:51.912894 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:17:56.292397 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f546d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:20:59.632932 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:24:03.202756 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f54950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:27:09.512974 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.0&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:30:13.012714 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48170>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:33:16.782734 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:36:20.232756 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=18.964 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f484b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:39:23.812748 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48470>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:42:28.132726 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.06&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f48950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:45:32.472842 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.096&api_key=2SN2O4NEQJ4UZ84T&field1=19.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c0f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:48:37.972713 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3cbf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:51:44.062894 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:54:48.472988 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.12&api_key=2SN2O4NEQJ4UZ84T&field1=19.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 06:57:54.532694 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.096 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:01:04.002294 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:04:15.227017 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c4b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:05:33.419448 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c3b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:06:51.583147 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f3c090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:08:09.747121 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57ceb30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:09:27.840569 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57cee30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:10:45.970692 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57cec70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:12:04.129985 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:13:22.267810 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:14:40.467214 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f438b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:15:58.606185 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f43710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:17:16.801222 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=19.19&api_key=2SN2O4NEQJ4UZ84T&field1=19.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f435d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
                                                                                                                                                                                                                                                                                                                                                                                                                                          2018-09-30 07:31:04.079392 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.88&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb584b850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:34:51.343917 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.81&api_key=2SN2O4NEQJ4UZ84T&field1=21.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5836dd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:36:13.020793 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.75&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb584bf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:37:37.876510 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.69&api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5867430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:38:57.395838 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.62&api_key=2SN2O4NEQJ4UZ84T&field1=20.69 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5867590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:40:21.660444 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.62&api_key=2SN2O4NEQJ4UZ84T&field1=20.69 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb58676b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:41:40.915753 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.56&api_key=2SN2O4NEQJ4UZ84T&field1=20.69 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5867830>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:43:04.996539 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.56&api_key=2SN2O4NEQJ4UZ84T&field1=20.62 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb58679b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:44:24.537324 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.5&api_key=2SN2O4NEQJ4UZ84T&field1=20.62 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5867af0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:45:52.284369 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.5&api_key=2SN2O4NEQJ4UZ84T&field1=20.596 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5867a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:46:07.234772 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.56&api_key=2SN2O4NEQJ4UZ84T&field1=20.62 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5867bf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:31:03.854252 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.94&api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:33:49.180199 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.06&api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805bd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:36:37.978654 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.084&api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:39:23.100512 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.12&api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:42:10.052529 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805530>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:44:54.458291 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:47:39.829646 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=20.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:50:24.292402 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.12&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:53:08.058945 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.024&api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:55:52.378079 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.0&api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb58226f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 07:58:37.571789 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.94&api_key=2SN2O4NEQJ4UZ84T&field1=20.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822830>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:01:23.823875 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.94&api_key=2SN2O4NEQJ4UZ84T&field1=20.774 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb58229b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:04:07.258261 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.94&api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822af0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:06:50.620841 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.964&api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:09:35.971884 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=20.94&api_key=2SN2O4NEQJ4UZ84T&field1=20.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:12:20.449181 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.0&api_key=2SN2O4NEQJ4UZ84T&field1=20.852 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:15:05.109898 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.0&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b030>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:17:50.297558 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.0&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b170>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:20:33.657991 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.0&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:23:18.860239 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.0&api_key=2SN2O4NEQJ4UZ84T&field1=20.88 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:26:03.350313 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.06&api_key=2SN2O4NEQJ4UZ84T&field1=20.94 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:28:48.539107 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.096&api_key=2SN2O4NEQJ4UZ84T&field1=20.964 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:31:32.857729 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=21.12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:34:17.100250 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.214&api_key=2SN2O4NEQJ4UZ84T&field1=21.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822fb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:37:02.540734 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=21.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:39:46.136607 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=21.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:42:32.216607 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=21.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb58224f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:45:15.823515 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.19&api_key=2SN2O4NEQJ4UZ84T&field1=21.06 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822170>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:48:00.137852 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.338&api_key=2SN2O4NEQJ4UZ84T&field1=21.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5822150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:50:46.298416 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.38&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57f0db0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:53:29.897219 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.31&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57f0b70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:56:13.498048 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.31&api_key=2SN2O4NEQJ4UZ84T&field1=21.134 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57f0c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 08:58:58.931861 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.31&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:01:43.176837 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.38&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805bf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:04:27.498178 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.416&api_key=2SN2O4NEQJ4UZ84T&field1=21.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:07:12.700320 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.56&api_key=2SN2O4NEQJ4UZ84T&field1=21.5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:09:57.196856 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.5&api_key=2SN2O4NEQJ4UZ84T&field1=21.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5805c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:12:40.617534 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.5&api_key=2SN2O4NEQJ4UZ84T&field1=21.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:15:25.098026 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.44&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:18:09.419860 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.38&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:20:54.696875 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.38&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:23:40.851545 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.38&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:26:25.260140 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.38&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b1d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:29:09.737903 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.352&api_key=2SN2O4NEQJ4UZ84T&field1=21.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5b9f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:31:55.177643 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.536&api_key=2SN2O4NEQJ4UZ84T&field1=21.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5bb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:34:40.313276 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.56&api_key=2SN2O4NEQJ4UZ84T&field1=21.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5bcb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:37:24.617189 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.56&api_key=2SN2O4NEQJ4UZ84T&field1=21.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5bdf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:40:09.022852 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.56&api_key=2SN2O4NEQJ4UZ84T&field1=21.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5bf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:42:53.350070 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.536&api_key=2SN2O4NEQJ4UZ84T&field1=21.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5f090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:45:38.697513 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.536&api_key=2SN2O4NEQJ4UZ84T&field1=21.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5f1d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2018-09-30 09:48:22.860140 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?field2=21.56&api_key=2SN2O4NEQJ4UZ84T&field1=21.366 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4f5f390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
                                                                                                                                                                                                                                                                                                                                                                                                                                          2018-09-30 11:18:31.516157 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.56 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501e470>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-30 11:20:21.990231 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=22.56 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501ee10>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-30 12:25:13.674951 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.38 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75027e70>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-30 12:38:11.543319 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.69 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75027630>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-30 12:41:53.110365 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.75 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501e610>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-30 12:43:43.510212 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=23.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501e910>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-30 13:05:57.940665 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=24.62 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501edf0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-30 13:11:30.870167 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=25.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75027030>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
2018-09-30 13:31:54.185484 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=27.31 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x758b19b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-30 13:54:51.438769 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=29.19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75027330>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-30 14:11:36.263217 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=28.81 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501e390>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-30 14:20:51.597857 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=28.44 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x758c55d0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2018-09-30 14:39:27.741237 | Error Connecting | ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: //update.json?api_key=2SN2O4NEQJ4UZ84T&field1=27.25 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7501e730>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
2018-09-30 14:43:51.536207 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:44:05.676658 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:44:19.234874 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:44:32.559147 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:44:47.659937 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:45:01.992514 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:45:14.911067 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:45:28.957331 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:45:40.927360 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:45:53.485230 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:46:07.241019 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:48:40.875957 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:50:01.980411 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:51:36.139494 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 14:52:56.746085 | Unhandled Exception | KeyError('ts_channel_id',)
2018-09-30 15:09:33.042680 | Unhandled Exception | KeyError('sensors',)
